version: '3'

services:
  mysql:
    build: ./docker/mysql
    container_name: ${CONTAINER_NAME_PREFIX}_mysql
    #    user: "999:999"
    volumes:
      - ${PWD}/docker/mysql/my.cnf:/etc/my.cnf
      #- ${PWD}/docker/mysql/data:/var/lib/mysql
      - volume-laravel-mysql:/var/lib/mysql
      - ${PWD}/docker/mysql/backup:/mysql_backup:rwx
      - ${PWD}/docker/mysql/init:/docker-entrypoint-initdb.d
    #      - ${PWD}/docker/mysql/logs:/var/log/mysql
    environment:
      MYSQL_DATABASE: ${LARAVEL_MYSQL_DATABASE}
      MYSQL_USER: ${LARAVEL_MYSQL_USER}
      MYSQL_PASSWORD: ${LARAVEL_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${LARAVEL_MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}
    ports:
      - ${LARAVEL_MYSQL_EXTERNAL_PORT}:${LARAVEL_MYSQL_INTERNAL_PORT}
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb_use_native_aio=0

  redis:
    image: redis:alpine
    container_name: ${CONTAINER_NAME_PREFIX}_redis
    ports:
      - ${REDIS_EXTERNAL_PORT}:${REDIS_INTERNAL_PORT}

  schemaspy_mysql:
    image: schemaspy/schemaspy
    container_name: ${CONTAINER_NAME_PREFIX}_schemaspy_mysql
    profiles: [ "debug" ]
    volumes:
      - ${PWD}/schemaspy/laravel_mysql/output:/output
      - ${PWD}/Docker/schemaspy/drivers/mysql:${LARAVEL_MYSQL_DRIVERS_DIR}
    depends_on:
      - laravel-mysql
    command: >
      java -jar schemaspy.jar
      -t ${LARAVEL_DB_TYPE}
      -dp ${LARAVEL_MYSQL_DRIVERS_DIR}
      -host ${LARAVEL_MYSQL_HOST}
      -port ${LARAVEL_MYSQL_INTERNAL_PORT}
      -db ${LARAVEL_MYSQL_DATABASE}
      -u ${LARAVEL_MYSQL_USER}
      -p ${LARAVEL_MYSQL_PASSWORD}
      -s ${LARAVEL_MYSQL_SCHEMA}
      -connprops allowPublicKeyRetrieval\\=false useSSL\\=false

  schemaspy_nginx:
    image: nginx:1.13.9-alpine
    container_name: ${CONTAINER_NAME_PREFIX}_nginx
    volumes:
      - ${PWD}/schemaspy/laravel_mysql/output:/var/www/html/schemaspy/laravel_mysql:ro
      - ${PWD}/docker/nginx/schemaspy_laravel_mysql.conf:/etc/nginx/conf.d/schemaspy_laravel_mysql.conf:ro
      - ${PWD}/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ${PWD}/php-fpm/src:/usr/share/nginx/html
    #      - ${PWD}/.env:/usr/share/nginx/html/.env
    ports:
      - ${NGINX_EXTERNAL_PORT}:${NGINX_INTERNAL_PORT}
      - ${NGINX_SCHEMASPY_LARAVEL_MYSQL_EXTERNAL_PORT}:${NGINX_SCHEMASPY_LARAVEL_MYSQL_INTERNAL_PORT}
    environment:
      - LANG=ja_JP.UTF-8
      - TZ=Asia/Tokyo
    command: "nginx -g 'daemon off;'"

  cake-nginx:
    container_name: ${CONTAINER_NAME_PREFIX}_cake-nginx
    build: ./docker/laravel_nginx
    depends_on:
      - laravel-app
    ports:
      - ${LARAVEL_EXTERNAL_PORT}:${LARAVEL_INTERNAL_PORT}
    volumes:
      - ${PWD}/fw/laravel9:/src
      - ${PWD}/docker/laravel_nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/docker/laravel_nginx/log:/var/log/nginx
  # Todo     - ./docker/laravel_nginx/logs:/src/docker/nginx/logs

  cake-app:
    container_name: ${CONTAINER_NAME_PREFIX}_cake-app
    build: ./docker/laravel_app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    #    depends_on:
    #      - laravel-mysql
    volumes:
      - ${PWD}/fw/laravel9:/src
      #      - ./docker/laravel_app/php.ini:/usr/local/etc/php/php.ini
      - ${PWD}/docker/laravel_app/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      XDEBUG_PORT: ${XDEBUG_PORT}
      XDEBUG_KEY: ${XDEBUG_KEY}


networks:
  default:
    external: false
volumes:
  volume-laravel-mysql:
    name: ${CONTAINER_NAME_PREFIX}_mysql
    labels:
      keep: true
