version: '3'

services:
  openapi:
    build: ./docker/openapi
    container_name: ${CONTAINER_NAME_PREFIX}_openapi
    volumes:
      - ${PWD}/generated/openapi/openapi.json:/app/generated/openapi/openapi.json
      - ${PWD}/openapi:/app/src
      - ${PWD}/docker/openapi/package.json:/app/package.json
    tty: true

  prism:
    build: ./docker/prism
    container_name: ${CONTAINER_NAME_PREFIX}_prism
    depends_on:
      - openapi
    command: 'mock -h 0.0.0.0 -d /app/openapi.json'
    volumes:
      - ${PWD}/generated/openapi/openapi.json:/app/openapi.json
    ports:
      - "${PRISM_CLIENT_PORT}:4010"

  swagger-ui:
    build: ./docker/swagger_ui_react
    container_name: ${CONTAINER_NAME_PREFIX}_swagger-ui
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=${SWAGGER_UI_CLIENT_PORT}
    volumes:
      - ${PWD}/docker/swagger_ui_react/public:/app/html/public
      - ${PWD}/docker/swagger_ui_react/src:/app/html/src
      - ${PWD}/generated/openapi/openapi.json:/app/html/public/openapi.json
    command: sh -c "yarn start"
    ports:
      - "${SWAGGER_UI_CLIENT_PORT}:${SWAGGER_UI_CLIENT_PORT}"
    working_dir: /app/html
    tty: true

  schemaspy_laravel_mysql:

    image: schemaspy/schemaspy
    container_name: ${CONTAINER_NAME_PREFIX}_schemaspy_laravel_mysql
    profiles: [ "debug" ]
    volumes:
      - ${PWD}/schemaspy/laravel_mysql/output:/output
      - ${PWD}/Docker/schemaspy/drivers/mysql:${LARAVEL_MYSQL_DRIVERS_DIR}
    depends_on:
      - laravel-mysql
    command: >
      java -jar schemaspy.jar
      -t ${LARAVEL_DB_TYPE}
      -dp ${LARAVEL_MYSQL_DRIVERS_DIR}
      -host ${LARAVEL_MYSQL_HOST}
      -port ${LARAVEL_MYSQL_INTERNAL_PORT}
      -db ${LARAVEL_MYSQL_DATABASE}
      -u ${LARAVEL_MYSQL_USER}
      -p ${LARAVEL_MYSQL_PASSWORD}
      -s ${LARAVEL_MYSQL_SCHEMA}
      -connprops allowPublicKeyRetrieval\\=false useSSL\\=false

  nginx:
    image: nginx:1.13.9-alpine
    container_name: ${CONTAINER_NAME_PREFIX}_nginx
    volumes:
      - ${PWD}/schemaspy/laravel_mysql/output:/var/www/html/schemaspy/laravel_mysql:ro
      - ${PWD}/docker/nginx/schemaspy_laravel_mysql.conf:/etc/nginx/conf.d/schemaspy_laravel_mysql.conf:ro
      - ${PWD}/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ${PWD}/php-fpm/src:/usr/share/nginx/html
    #      - ${PWD}/.env:/usr/share/nginx/html/.env
    ports:
      - ${NGINX_SCHEMASPY_LARAVEL_MYSQL_EXTERNAL_PORT}:${NGINX_SCHEMASPY_LARAVEL_MYSQL_INTERNAL_PORT}
      - ${NGINX_EXTERNAL_PORT}:${NGINX_INTERNAL_PORT}
    environment:
      - LANG=ja_JP.UTF-8
      - TZ=Asia/Tokyo
    command: "nginx -g 'daemon off;'"

  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - ${PWD}/php-fpm/src:/usr/share/nginx/html
      #- ${DIR_PATH}/${PHP_FPM_HOST_DIR}/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      #- ${DIR_PATH}/${PHP_FPM_HOST_DIR}/php.ini:/usr/local/etc/php/php.ini
    env_file:
      - .env
    working_dir: /usr/share/nginx/html

  laravel-nginx:
    container_name: ${CONTAINER_NAME_PREFIX}_laravel-nginx
    build: ./docker/laravel_nginx
    depends_on:
      - laravel-app
    ports:
      - ${LARAVEL_EXTERNAL_PORT}:${LARAVEL_INTERNAL_PORT}
    volumes:
      - ${PWD}/fw/laravel9:/src
      - ${PWD}/docker/laravel_nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/docker/laravel_nginx/log:/var/log/nginx
  # Todo     - ./docker/laravel_nginx/logs:/src/docker/nginx/logs

  laravel-app:
    container_name: ${CONTAINER_NAME_PREFIX}_laravel-app
    build: ./docker/laravel_app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    #    depends_on:
    #      - laravel-mysql
    volumes:
      - ${PWD}/fw/laravel9:/src
      #      - ./docker/laravel_app/php.ini:/usr/local/etc/php/php.ini
      - ${PWD}/docker/laravel_app/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      XDEBUG_PORT: ${XDEBUG_PORT}
      XDEBUG_KEY: ${XDEBUG_KEY}

  laravel-mysql:
    build: ./docker/mysql
    container_name: ${CONTAINER_NAME_PREFIX}_laravel_mysql
    #    user: "999:999"
    volumes:
      - ${PWD}/docker/mysql/my.cnf:/etc/my.cnf
      #- ${PWD}/docker/mysql/data:/var/lib/mysql
      - volume-laravel-mysql:/var/lib/mysql
      - ${PWD}/docker/mysql/backup:/mysql_backup:rwx
      - ${PWD}/docker/mysql/init:/docker-entrypoint-initdb.d
    #      - ${PWD}/docker/mysql/logs:/var/log/mysql
    environment:
      MYSQL_DATABASE: ${LARAVEL_MYSQL_DATABASE}
      MYSQL_USER: ${LARAVEL_MYSQL_USER}
      MYSQL_PASSWORD: ${LARAVEL_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${LARAVEL_MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}
    ports:
      - ${LARAVEL_MYSQL_EXTERNAL_PORT}:${LARAVEL_MYSQL_INTERNAL_PORT}
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb_use_native_aio=0


  laravel-redis:
    image: redis:alpine
    container_name: ${CONTAINER_NAME_PREFIX}_laravel-redis
    ports:
      - ${REDIS_EXTERNAL_PORT}:${REDIS_INTERNAL_PORT}

  elasticsearch:
    build: ./docker/elasticsearch
    container_name: ${CONTAINER_NAME_PREFIX}_elasticsearch
    profiles: [ "debug" ]
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.monitoring.collection.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - ${ELASTICSEARCH_EXTERNAL_PORT1}:${ELASTICSEARCH_INTERNAL_PORT1}
      - ${ELASTICSEARCH_EXTERNAL_PORT2}:${ELASTICSEARCH_INTERNAL_PORT2}
    tty: true

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    container_name: ${CONTAINER_NAME_PREFIX}_kibana
    profiles: [ "debug" ]
    ports:
      - ${KIBANA_EXTERNAL_PORT}:${KIBANA_INTERNAL_PORT}
    mem_limit: 1g
    memswap_limit: 1g
    environment:
      #- ELASTICSEARCH_HOSTS = http://elasticsearch:${ELASTICSEARCH_INTERNAL_PORT1}
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      #- ELASTICSEARCH_HOSTS='["http://elasticsearch:9200"]'
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - SERVER_PUBLICBASEURL=http://host.docker.internal:${KIBANA_EXTERNAL_PORT}
      #- XPACK_SECURITY_ENABLED=false
    depends_on:
      - elasticsearch

networks:
  default:
    external: false
volumes:
  volume-laravel-mysql:
    name: ${CONTAINER_NAME_PREFIX}_laravel_mysql
    labels:
      keep: true
