version: '3'

services:
  openapi:
    build: ./docker/openapi
    container_name: ${PRISM_CONTAINER_NAME_PREFIX}_openapi
    volumes:
      - ${DIR}/generated:/app/generated
      - ${DIR}/openapi:/app/src
      - ${DIR}/docker/openapi/package.json:/app/package.json
    tty: true

  prism:
    build: ./docker/prism
    container_name: ${PRISM_CONTAINER_NAME_PREFIX}_prism
    command: 'mock -h 0.0.0.0 -d /app/openapi.json'
    volumes:
      - ${DIR}/generated/openapi/openapi.json:/app/openapi.json
    ports:
      - '${PRISM_CLIENT_PORT}:4010'

  swagger-ui:
    build: ./docker/swagger_ui_react
    container_name: ${PRISM_CONTAINER_NAME_PREFIX}_swagger-ui
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=${SWAGGER_UI_CLIENT_PORT}
    volumes:
      - ${DIR}/docker/swagger_ui_react/public:/app/html/public
      - ${DIR}/docker/swagger_ui_react/src:/app/html/src
      - ${DIR}/generated/openapi/openapi.json:/app/html/public/openapi.json
#    command: sh -c "cd html && yarn start"
    ports:
      - "${SWAGGER_UI_CLIENT_PORT}:${SWAGGER_UI_CLIENT_PORT}"
    working_dir: /app/html
    tty: true

#  swagger-ui:
#     image: swaggerapi/swagger-ui
#     container_name: ${PRISM_CONTAINER_NAME_PREFIX}_swagger-ui
#     volumes:
#       - ${DIR}/generated/openapi/openapi.json:/openapi.json
# #      - ${DIR}/docker/swagger_ui/html:/usr/share/nginx/html
#     environment:
#       SWAGGER_JSON: /openapi.json
#     ports:
#       - "${SWAGGER_UI_CLIENT_PORT}:${SWAGGER_UI_SERVER_PORT}"

  schemaspy_mysql:
    image: schemaspy/schemaspy
    container_name: ${PRISM_CONTAINER_NAME_PREFIX}_schemaspy_mysql
    volumes:
      - ${DIR}/schemaspy/mysql/output:/output
      - ${DIR}/Docker/schemaspy/drivers/mysql:${MYSQL_DRIVERS_DIR}
    depends_on:
      - mysql
    command: >
      java -jar schemaspy.jar
      -t ${DB_TYPE_MYSQL}
      -dp ${MYSQL_DRIVERS_DIR}
      -host ${MYSQL_HOST}
      -port ${MYSQL_INTERNAL_PORT}
      -db ${MYSQL_DATABASE}
      -u ${MYSQL_USER}
      -p ${MYSQL_PASSWORD}
      -s ${MYSQL_SCHEMA}
      -connprops allowPublicKeyRetrieval\\=false useSSL\\=false

  schemaspy_postgres:
    image: schemaspy/schemaspy
    container_name: ${PRISM_CONTAINER_NAME_PREFIX}_schemaspy_postgres
    volumes:
      - ${DIR}/schemaspy/postgres/output:/output
      - ${DIR}/Docker/schemaspy/drivers:${POSTGRES_DRIVERS_DIR}
    depends_on:
      - postgres
    command: >
      java -jar schemaspy.jar
      -t ${DB_TYPE_POSTGRES}
      -dp ${POSTGRES_DRIVERS_DIR}
      -host ${POSTGRES_HOST}
      -port ${POSTGRES_INTERNAL_PORT}
      -db ${POSTGRES_DB}
      -u ${POSTGRES_USER}
      -p ${POSTGRES_PASSWORD}
      -connprops useSSL\\\\=false -all

  nginx:
    image: nginx:1.13.9-alpine
    container_name: ${PRISM_CONTAINER_NAME_PREFIX}_nginx
    volumes:
      - ${DIR}/schemaspy/mysql/output:/var/www/html/schemaspy/mysql:ro
      - ${DIR}/schemaspy/postgres/output:/var/www/html/schemaspy/postgres:ro
      - ${DIR}/Docker/nginx/schemaspy_mysql.conf:/etc/nginx/conf.d/schemaspy_mysql.conf:ro
      - ${DIR}/Docker/nginx/schemaspy_postgres.conf:/etc/nginx/conf.d/schemaspy_postgres.conf:ro
    ports:
      - ${NGINX_SCHEMASPY_MYSQL_EXTERNAL_PORT}:${NGINX_SCHEMASPY_MYSQL_INTERNAL_PORT}
      - ${NGINX_SCHEMASPY_POSTGRES_EXTERNAL_PORT}:${NGINX_SCHEMASPY_POSTGRES_INTERNAL_PORT}
    environment:
      - LANG=ja_JP.UTF-8
      - TZ=Asia/Tokyo
    command: "nginx -g 'daemon off;'"

  phpmig:
    build: ./Docker/phpmig
    container_name: ${PRISM_CONTAINER_NAME_PREFIX}_phpmig
    volumes:
      - ${DIR}//Docker/phpmig/src/:/app/src
      - ${DIR}/Docker/phpmig/php.ini:/usr/local/etc/php/php.ini
      - ${DIR}/Docker/phpmig/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ${DIR}/phpmig:/phpmig
    depends_on:
      - mysql
      - postgres
    environment:
      TARGET_DB: ${TARGET_DB}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_INTERNAL_PORT: ${MYSQL_INTERNAL_PORT}
      XDEBUG_PORT: ${XDEBUG_PORT}
      XDEBUG_KEY: ${XDEBUG_KEY}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_INTERNAL_PORT: ${POSTGRES_INTERNAL_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    tty: true

  mysql:
    image: mysql:8.0
    container_name: ${PRISM_CONTAINER_NAME_PREFIX}_mysql
    user: "1000:50"
    volumes:
      - ${DIR}/Docker/mysql/my.cnf:/etc/my.cnf
      - ${DIR}/Docker/mysql/data:/var/lib/mysql
      - ${DIR}/Docker/mysql/backup:/tmp/mysql
      - ${DIR}/Docker/mysql/init:/docker-entrypoint-initdb.d
      - ${DIR}/Docker/mysql/logs:/var/log/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}
    ports:
      - ${MYSQL_EXTERNAL_PORT}:${MYSQL_INTERNAL_PORT}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb_use_native_aio=0

  postgres:
    image: postgres:14
    container_name: ${PRISM_CONTAINER_NAME_PREFIX}_postgres
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT}
    volumes:
      - ${DIR}/Docker/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}
