openapi: 3.0.2

info:
  title: Structured OpenAPI Schema
  description: descriptionn
  version: '1.0'

servers:
  - url: http://develop.local:49159
    description: Mock server (prism)
  - url: http://develop.local:{port}/{api_version}
    description: Develop server
    variables:
      api_version:
        default: 'v1'
        enum:
          - 'v1'
          - 'v2'
          - 'v3'
      port:
        default: '49170'
        enum:
          - '49170'
          - '8080'
          - '8081'
          - '8082'

tags:
  - name: user
    description: User control

paths:
  /users/offset/{offset}/limit/{limit}:
    $ref: ./paths/users/users_list.yml
  /users:
    $ref: ./paths/users/users.yml
  /users/{user_id}:
    $ref: ./paths/users/users_id.yml
